name: HMDA Light Data Transformations Pipeline

on: 
  workflow_dispatch: 
    inputs: 
      source_bucket: 
        description: 'Soure S3 bucket name'
        required: true
      target_bucket: 
        description: 'Target S3 bucket name'
        required: true 
      raw_prefix:
        description: 'Source prefix in S3'
        required: true 
      clean_prefix: 
        description: 'The prefix of the cleaned files'
        required: true
      clean_file_base: 
        description: 'Base name of the output files'
        required: true 
      aws_region:
        description: 'AWS region'
        default: 'us-east-1'
  
jobs: 
  light-data-transformations: 
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read 
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::769392325318:role/github-actions-run-hmda-pipeline
          aws-region: ${{ github.event.inputs.aws_region }}
      
      - name: Verify AWS identity
        run : aws sts get-caller-identity

      - name: Run Summary Script
        run: |
          python scripts/simple_transformations/main.py \
            --source-bucket "${{ github.event.inputs.source_bucket }}" \
            --target-bucket "${{ github.event.inputs.target_bucket }}" \
            --raw-prefix "${{ github.event.inputs.raw_prefix }}" \
            --clean-prefix "${{ github.event.inputs.clean_prefix }}" \
            --clean-file-base "${{ github.event.inputs.clean_file_base }}"

